### ISSUE TITLE
Errores al hacer grunt build para deployment

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#96]
No se ve el catálogo, y en web inspector arroja:

Uncaught Error: [$injector:modulerr] Failed to instantiate module ngCkanApp due to:
Error: [$injector:unpr] Unknown provider: a
http://errors.angularjs.org/1.3.12/$injector/unpr?p0=a
    at http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:3:20442
    at http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:4:6478
    at d (http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:4:5648)
    at Object.e [as invoke] (http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:4:5985)
    at d (http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:4:5036)
    at http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:4:5160
    at f (http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:3:20827)
    at n (http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:4:4937)
    at Sb (http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:4:6627)
    at h (http://mxabierto.github.io/ng-ckan/scripts/vendor.06bab9ea.js:3:26459)

**Comment by rodowi** [comment]
Prueba haciendo `grunt build`y sale un error de ng:Annotate

Running "ngAnnotate:dist" (ngAnnotate) task
Warning: Cannot assign to read only property '$methodName' of false Use --force to continue.

Aborted due to warnings.


Lo pasé haciendo --force pero tal vez por eso está fallando en el deployment
